// <auto-generated />
using System;
using BusStopManagement.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusStopManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202140621_UpdatedBusStopEntityAndAddedSchemaConstraints")]
    partial class UpdatedBusStopEntityAndAddedSchemaConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusStopManagement.Core.Domain.Entities.BusStop", b =>
                {
                    b.Property<Guid>("BusStopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusStopAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusStopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusStopID");

                    b.ToTable("BusStop", (string)null);
                });

            modelBuilder.Entity("BusStopManagement.Core.Domain.Entities.Departure", b =>
                {
                    b.Property<Guid>("DepartureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusStopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTimeOfDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("NumberOfSeats")
                        .HasColumnType("tinyint");

                    b.HasKey("DepartureID");

                    b.HasIndex("BusStopID");

                    b.ToTable("Departure", (string)null);
                });

            modelBuilder.Entity("BusStopManagement.Core.Domain.Entities.Departure", b =>
                {
                    b.HasOne("BusStopManagement.Core.Domain.Entities.BusStop", "BusStop")
                        .WithMany("Departures")
                        .HasForeignKey("BusStopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusStop");
                });

            modelBuilder.Entity("BusStopManagement.Core.Domain.Entities.BusStop", b =>
                {
                    b.Navigation("Departures");
                });
#pragma warning restore 612, 618
        }
    }
}
